### ISSUE TITLE
Make tests run as independent scripts

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-python#13]
The three tests return the same error due to a path problem:
```
  File "test_validate.py", line 7, in <module>
    from tests import PG_FOLDER, LOCAL_PROCESSES_FOLDER
ModuleNotFoundError: No module named 'tests'
```

I followed the procedure to install the parser, creating a new environment and running setup.py

**Comment by lforesta** [comment]
Hi, I just tried cloning from master, creating the env, activating it, and running setup.py and then running tests. They worked for me.

Did you clone from master?
Can I double check that you ran the tests from within the environment?

**Comment by clausmichele** [comment]
I've just double checked, cloned again and followed the procedure with the same result. The only difference is that I use Conda instead of Miniconda, but there shouldn't be differences.
```
michele:~/test_parser$ git clone https://github.com/Open-EO/openeo-pg-parser-python.git
Cloning into 'openeo-pg-parser-python'...
remote: Enumerating objects: 340, done.
remote: Counting objects: 100% (340/340), done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 340 (delta 171), reused 285 (delta 126), pack-reused 0
Receiving objects: 100% (340/340), 90.88 KiB | 788.00 KiB/s, done.
Resolving deltas: 100% (171/171), done.
michele:~/test_parser/openeo-pg-parser-python$ conda env create -f conda_environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
pip-20.0.2           | 1.7 MB    | ############ | 100% 
cryptography-2.9.2   | 556 KB    | ############ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate openeo-pg-parser-python
#
# To deactivate an active environment, use
#
#     $ conda deactivate

michele:~/test_parser/openeo-pg-parser-python$ conda activate openeo-pg-parser-python
(openeo-pg-parser-python) michele:~/test_parser/openeo-pg-parser-python$ python setup.py install
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
  WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
running install
running bdist_egg
running egg_info
creating src/openeo_pg_parser_python.egg-info
writing src/openeo_pg_parser_python.egg-info/PKG-INFO
writing dependency_links to src/openeo_pg_parser_python.egg-info/dependency_links.txt
writing requirements to src/openeo_pg_parser_python.egg-info/requires.txt
writing top-level names to src/openeo_pg_parser_python.egg-info/top_level.txt
writing manifest file 'src/openeo_pg_parser_python.egg-info/SOURCES.txt'
writing manifest file 'src/openeo_pg_parser_python.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/openeo_pg_parser_python
copying src/openeo_pg_parser_python/translate.py -> build/lib/openeo_pg_parser_python
copying src/openeo_pg_parser_python/validate.py -> build/lib/openeo_pg_parser_python
copying src/openeo_pg_parser_python/__init__.py -> build/lib/openeo_pg_parser_python
copying src/openeo_pg_parser_python/graph.py -> build/lib/openeo_pg_parser_python
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/openeo_pg_parser_python
copying build/lib/openeo_pg_parser_python/translate.py -> build/bdist.linux-x86_64/egg/openeo_pg_parser_python
copying build/lib/openeo_pg_parser_python/validate.py -> build/bdist.linux-x86_64/egg/openeo_pg_parser_python
copying build/lib/openeo_pg_parser_python/__init__.py -> build/bdist.linux-x86_64/egg/openeo_pg_parser_python
copying build/lib/openeo_pg_parser_python/graph.py -> build/bdist.linux-x86_64/egg/openeo_pg_parser_python
byte-compiling build/bdist.linux-x86_64/egg/openeo_pg_parser_python/translate.py to translate.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/openeo_pg_parser_python/validate.py to validate.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/openeo_pg_parser_python/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/openeo_pg_parser_python/graph.py to graph.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openeo_pg_parser_python.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openeo_pg_parser_python.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openeo_pg_parser_python.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openeo_pg_parser_python.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openeo_pg_parser_python.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/openeo_pg_parser_python.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/openeo_pg_parser_python-1.0.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing openeo_pg_parser_python-1.0.0-py3.6.egg
creating /home/michele/anaconda3/envs/openeo-pg-parser-python/lib/python3.6/site-packages/openeo_pg_parser_python-1.0.0-py3.6.egg
Extracting openeo_pg_parser_python-1.0.0-py3.6.egg to /home/michele/anaconda3/envs/openeo-pg-parser-python/lib/python3.6/site-packages
Adding openeo-pg-parser-python 1.0.0 to easy-install.pth file

Installed /home/michele/anaconda3/envs/openeo-pg-parser-python/lib/python3.6/site-packages/openeo_pg_parser_python-1.0.0-py3.6.egg
Processing dependencies for openeo-pg-parser-python==1.0.0
Finished processing dependencies for openeo-pg-parser-python==1.0.0
(openeo-pg-parser-python) michele:~/test_parser/openeo-pg-parser-python$ cd tests/(openeo-pg-parser-python) michele:~/test_parser/openeo-pg-parser-python/tests$ python test_
test_graph.py      test_translate.py  test_validate.py   
(openeo-pg-parser-python) michele:~/test_parser/openeo-pg-parser-python/tests$ python test_graph.py 
Traceback (most recent call last):
  File "test_graph.py", line 5, in <module>
    from tests import PG_FOLDER
ModuleNotFoundError: No module named 'tests'
```

**Comment by lforesta** [comment]
ah, no need to go into the tests  folder, remain in the top folder and run:

```
python setup.py test
```

**Comment by clausmichele** [comment]
Ok sorry, I was using the 0.4 version before and they were usable as python scripts.
The result is the following, seems ok:
```
tests/test_graph.py::test_sort_process_graph PASSED                                                                                                                                               [ 16%]
tests/test_translate.py::test_translate_process_graph PASSED                                                                                                                                      [ 33%]
tests/test_translate.py::test_process_graph_not_found PASSED                                                                                                                                      [ 50%]
tests/test_validate.py::test_validate_process_graph_local PASSED                                                                                                                                  [ 66%]
tests/test_validate.py::test_validate_process_graph_remote PASSED                                                                                                                                 [ 83%]
tests/test_validate.py::test_validate_wrong_band PASSED                                                                                                                                           [100%]

---------- coverage: platform linux, python 3.6.10-final-0 -----------
Name                                       Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------------
src/openeo_pg_parser_python/__init__.py        7      2      0      0    71%   8-9
src/openeo_pg_parser_python/graph.py         154     21     80     12    83%   72->73, 73-74, 106->107, 107, 130-137, 153, 213->219, 215->216, 216-217, 226, 312->313, 313, 315->318, 318-319, 345->349, 349, 370->374, 414->415, 415, 416->411, 419->422, 442->451, 451-452
src/openeo_pg_parser_python/translate.py     150      5     80      7    95%   272->273, 273, 275->283, 283, 306->318, 309->304, 318, 341->345, 345->348, 348, 408->411, 411
src/openeo_pg_parser_python/validate.py       83     12     44      5    85%   74->77, 77-78, 98->102, 102-106, 135->136, 136-138, 146->147, 147-150, 191->190
--------------------------------------------------------------------------------------
TOTAL                                        394     40    204     24    88%
```

**Comment by lforesta** [comment]
> Ok sorry, I was using the 0.4 version before and they were usable as python scripts.

Yes, we should make sure they can be used again independently, @claxn could you add this to the changes you're working on?

**Comment by claxn** [comment]
@clausmichele : Thanks for reporting this! I would always suggest to run tests with `python setup.py test` in the root directory. This is due to that unittest/pytest internally sets its source directories (adds them to the python path, etc.), which makes it easier for setting up tests, but does not allow to run individual python test files, sometimes, depending on what is where defined within tests, e.g. global variables. Anyway I restructured the tests a bit, now you it works in both ways. Please find the latest changes in the branch `tow_v1.0`, but keep in mind that it now already works with v1.0 process graphs. Please keep on reporting issues if you find some, we appreciate it!
